### PR TITLE
Use 12 instead of 0, PM starts at 12, not 13

### PR DESCRIPTION
**Pull request by doolse**
I'm hoping the rules for 12 hour time are the same everywhere.. 
noon should be:
12:00 PM 
instead of:
00:00 AM

### CODE REVIEW

**Comment by garyb** [comment]
I agree that 00:00 AM is wrong, but I think it's more common that 12:00 AM is midnight and 12:00 PM is noon. A quick google suggests that it's neither AM or PM and should be avoided in favour of "12 noon" and "12 midnight", but we probably don't want to do that for the purposes of this.

**Comment by doolse** [comment]
Just to be clear - old behaviour was:
00:00 -> 00:00 AM
...
11:00 -> 11:00 AM
12:00 -> 00:00 AM
13:00 -> 01:00 PM
...

The patch changes this to:
00:00 -> 12:00 AM
...
11:00 -> 11:00 AM
12:00 -> 12:00 PM
13:00 -> 01:00 PM
...

I think we all agree this is what we want?

**Comment by garyb** [comment]
Oh, sorry! I totally misread your original comment, I should have just looked at the code. :smile:

:+1: from me, but I'll let @cryogenian have his say too.

**Comment by cryogenian** [comment]
:+1: Thank you very much!

**Pull request merged**
